more fixes and tests
Signed-off-by: Denis Zalevskiy <denis.zalevskiy@jolla.com>

diff --git a/tests/test-vault-sync b/tests/test-vault-sync
--- a/tests/test-vault-sync
+++ b/tests/test-vault-sync
@@ -9,7 +9,7 @@ source $src/testing-common-vault.sh
 create_test_dir
 
 write_text() {
-    echo -ne "$1" > $2
+    echo -ne "$1" > $2 || test_failed "Can't write '$1' to $2"
 }
 
 write_random() {
@@ -34,13 +34,28 @@ dump_curdir_tree() {
 
 
 storage_path() {
-    echo $storage/root/$1
+    local parts=($storage root $@)
+    printf '/%s' "${parts[@]%/}"
 }
 
-check_home_storage_same_filenames() {
+home_path() {
+    local parts=($test_home $@)
+    printf '/%s' "${parts[@]%/}"
+}
+
+acceptable_diff=
+check_home_storage_same_content() {
     cd $(storage_path) && dump_curdir_tree > $test_dir/find_src
     cd $test_home && dump_curdir_tree > $test_dir/find_dst
-    diff $test_dir/find_src $test_dir/find_dst || error 11 "Tree is not fully copied?"
+    diff $test_dir/find_src $test_dir/find_dst >$test_out 2>$test_err
+    if [ $? -ne 0 ]; then
+        sorted_diff=$(cat $test_out | grep '^[<>]' | sort)
+        if [ "$sorted_diff" != "$acceptable_diff" ]; then
+            trace "GOT:$sorted_diff"
+            trace "NEED:$acceptable_diff"
+            test_failed 65 "Tree is not fully copied? Check diff"
+        fi
+    fi
 }
 
 create_test_dirs_and_vault() {
@@ -49,92 +64,229 @@ create_test_dirs_and_vault() {
     cd_vault_and_check_it
 }
 
-NEXT_TEST "Basic copy"
+NEXT_TEST "Import-depth-1"
+
 create_test_dirs_and_vault
-vault_sync_opts="-a import -r"
-basic_vault_import_single() {
+
+vault_sync_opts="NOT_SET_YET"
+vault_sync_opts_aux="NOT_SET_YET"
+
+vault_sync_opts_set() {
+    trace "vault-sync opts: $@"
+    vault_sync_opts="$@ $vault_sync_opts_aux"
+}
+
+
+basic_test_import_single() {
     trace "Import $1 to $test_home"
-    vault-sync $vault_sync_opts $1 $test_home || error 21 "copy existed with $?"
+    vault-sync $vault_sync_opts $1 $test_home || test_failed 21 "copy existed with $?"
     if [ $# -ge 2 ]; then
         ${@:2}
     fi
-    check_home_storage_same_filenames
+    check_home_storage_same_content
     rm $1 -rf
     rm $test_home/* -rf
-    [[ $(find $test_home | wc -l) -eq 1 ]] || error 22 "Test home should be empty"
+    [[ $(find $test_home | wc -l) -eq 1 ]] || test_failed 22 "Test home should be empty"
 }
-test_step "empty directory"
-entry_name=$(storage_path d0)
-mkdir -p $entry_name
-basic_vault_import_single $entry_name 
 
-basic_steps_wo_dir() {
-    test_step "empty file" $1
-    entry_name=$(storage_path f1)
-    touch $entry_name
-    basic_vault_import_single $entry_name
+basic_test_src_list=
+basic_test_import_multiply() {
+    trace "Import $basic_test_src_list to $test_home"
+    vault-sync $vault_sync_opts $basic_test_src_list $test_home \
+        || test_failed 21 "copy existed with $?"
+    if [ $# -ge 1 ]; then
+        ${@}
+    fi
+    check_home_storage_same_content
+    rm $basic_test_src_list -rf
+    rm $test_home/* -rf
+    [[ $(find $test_home | wc -l) -eq 1 ]] || test_failed 22 "Test home should be empty"
+}
 
-    test_step "1-sym file" $1
-    entry_name=$(storage_path f2)
-    write_text "2" $entry_name
-    basic_vault_import_single $entry_name
+basic_test_is_one_src=test_failed
+entry_name="THIS_IS_NOT_SET_YET"
+basic_test_import_if_single() {
+    if $basic_test_is_one_src; then
+        basic_test_import_single $entry_name ${@:2}
+    else
+        basic_test_src_list="$basic_test_src_list $entry_name"
+    fi
+}
 
-    test_step "longer text" $1
-    entry_name=$(storage_path f3)
-    write_text "0123456789 0123456789" $entry_name
-    basic_vault_import_single $entry_name
+basic_is_expect_empty_home=test_failed
 
-    test_step "big file (> chunk size)" $1
-    entry_name=$(storage_path big4)
-    write_random 1024 1058 $entry_name
-    basic_vault_import_single $entry_name
+# functions to create different node types
 
-    test_step "symlink" $1
-    entry_name=$(storage_path ln1)
-    target_name=$storage/f1
-    touch $target_name
-    ln -s $target_name $entry_name
-    basic_vault_import_single $entry_name
+basic_test_mkdir() {
+    entry_name=$(storage_path $@)
+    mkdir -p $entry_name
+    $basic_is_expect_empty_home || mkdir -p $(home_path $@)
+}
 
-    test_step "rel symlink" $1
-    entry_name=$(storage_path ln1)
-    target_name=../f1
+basic_test_touch() {
+    entry_name=$(storage_path $@)
+    touch $entry_name \
+        && ($basic_is_expect_empty_home || touch $(home_path $@)) \
+        || test_failed 11 "Trouble touching ($@)"
+}
+
+basic_test_write() {
+    entry_name=$(storage_path ${@:2})
+    write_text $1 $entry_name \
+        && ($basic_is_expect_empty_home || write_text "before" $(home_path ${@:2})) \
+        || test_failed 11 "Trouble writing text ($@)"
+}
+
+basic_test_write_random() {
+    local name=${@:3}
+    entry_name=$(storage_path $name)
+    write_random $1 $2 $entry_name \
+        && ($basic_is_expect_empty_home || write_random $1 $2 $(home_path $name)) \
+        || test_failed 11 "Trouble writing random ($@)"
+}
+
+basic_test_ln() {
+    entry_name=$(storage_path $1)
+    local target_name=$2
+    touch $target_name \
+        && ln -s $target_name $entry_name \
+        && ($basic_is_expect_empty_home || ln -s "before" $(home_path $1)) \
+            || test_failed 11 "Trouble symlinking ($@)"
+}
+
+basic_step_dir() {
+    test_step "empty-dir/$1"
+    basic_test_mkdir d0
+    basic_test_import_if_single $entry_name ${@:2}
+}
+
+basic_step_empty_file() {
+    test_step "empty-file/$1"
+    basic_test_touch f1
+    basic_test_import_if_single $entry_name ${@:2}
+}
+basic_step_1sym_file() {
+    test_step "1-sym-file/$1"
+    basic_test_write "2" f2
+    basic_test_import_if_single $entry_name ${@:2}
+}
+
+basic_step_text_file() {
+    test_step "longer-text/$1"
+    basic_test_write "0123456789_0123456789" f3
+    basic_test_import_if_single $entry_name ${@:2}
+}
+basic_step_big_file() {
+    test_step "file-greater-chunk-size/$1"
+    basic_test_write_random 1024 1058 f4
+    basic_test_import_if_single $entry_name ${@:2}
+}
+basic_step_link_file() {
+    test_step "symlink/$1"
+    basic_test_ln ln1 $storage/out1
+    basic_test_import_if_single $entry_name ${@:2}
+}
+basic_step_rel_link_file() {
+    test_step "rel-symlink/$1"
     pushd $(storage_path) 1>/dev/null
-    touch $target_name
-    ln -s $target_name $entry_name
+    basic_test_ln ln2 ../out1
     popd 1>/dev/null
-    basic_vault_import_single $entry_name
+    basic_test_import_if_single $entry_name ${@:2}
 }
-basic_steps_wo_dir "recursive"
 
-vault_sync_opts="-a import"
-test_step "Omit directory"
-entry_name=$(storage_path d_omit)
-mkdir -p $entry_name
-basic_vault_import_single $entry_name "rmdir $entry_name"
+basic_step_finalize() {
+    test_step "finalize/$1"
+    if ! $basic_test_is_one_src; then
+        basic_test_import_multiply ${@:2}
+    fi
+}
 
-basic_steps_wo_dir "non-recursive"
+basic_steps() {
+    basic_test_src_list=
+    basic_step_dir $@
+    basic_step_empty_file $@
+    basic_step_1sym_file $@
+    basic_step_text_file $@
+    basic_step_big_file $@
+    basic_step_link_file $@
+    basic_step_rel_link_file $@
+    basic_step_finalize $@
+}
 
-exit 0 # TODO
+test_vault_sync_rm_empty_dir() {
+    if $basic_test_is_one_src; then
+        [[ -d $entry_name ]] && rmdir $entry_name
+    else
+        for e in $(find $(storage_path)/. -type d -not -name '.' -and -not -name '..'); do
+        [[ -d $e ]] && rmdir $e
+        done
+    fi
+}
+
+basic_test_misc_options() {
+    local condition=$1
+    vault_sync_opts_set "-a import -r"
+    # all steps for single src with recursive copy
+    basic_steps "recursive/$condition"
+
+    # all steps for single src without recursive copy
+    vault_sync_opts_set "-a import"
+    if $basic_is_expect_empty_home; then
+        acceptable_diff=
+    else
+        acceptable_diff="> d:./d0"
+    fi
+    basic_steps "non-recursive/$condition" test_vault_sync_rm_empty_dir
+}
+
+basic_test_cycle() {
+    basic_test_is_one_src=true
+    basic_test_misc_options $1
+    # repeat same steps but for all sources at once
+    basic_test_is_one_src=false
+    basic_test_misc_options $1
+}
+
+basic_test_cycle_for_normal_and_binary() {
+    local cycle_step=$1    
+    basic_is_expect_empty_home=true
+    basic_test_cycle "empty-dst/$cycle_step"
+    basic_is_expect_empty_home=false
+    basic_test_cycle "existing-dst/$cycle_step"
+
+    test_step "recursive/2-level-dir/$cycle_step"
+    basic_is_expect_empty_home=true
+    basic_test_mkdir d0/d01
+    vault_sync_opts_set "-a import -r $vault_sync_opts_aux"
+    acceptable_diff=
+    basic_test_import_single $(storage_path d0)
+
+    test_step "non-recursive/2-level-dir/$cycle_step"
+    basic_test_mkdir d0/d01
+    vault_sync_opts_set "-a import"
+    acceptable_diff=$(cat <<EOF
+< d:./d0
+< d:./d0/d01
+EOF
+                   )
+    basic_test_import_single $(storage_path d0)
+
+    test_step "recursive/dir-with-entries/$cycle_step"
+    basic_is_expect_empty_home=true
+    basic_test_mkdir d0/d01
+    basic_test_touch d0/f01
+    basic_test_ln d0/l01 ./
+    vault_sync_opts_set "-a import -r"
+    acceptable_diff=
+    basic_test_import_single $(storage_path d0)
+}
+
+vault_sync_opts_aux=
+basic_test_cycle_for_normal_and_binary "text-mode"
+
+vault_sync_opts_aux="-b"
+basic_test_cycle_for_normal_and_binary "bin-mode"
+
+exit 0 #TODO
 
 NEXT_TEST "Copy when exists"
-create_test_dirs_and_vault
-# src
-mkdir -p $storage/d0
-touch $storage/f1
-write_text "2" $storage/f2
-write_text "0123456789 0123456789" $storage/f3
-write_random 1024 1058 $storage/big_f4
-# dst
-mkdir -p $test_home/d0
-write_text "before" $test_home/f1
-write_text "before" $test_home/f2
-write_text "before" $test_home/f3
-write_random 1024 512 $test_home/big_f4
-vault-sync -a import -r $storage $test_home || error 22 "copy existed with $?"
-check_home_storage_same_filenames
-
-NEXT_TEST "Copy binary"
-create_test_dirs_and_vault
-write_text "0123456789 0123456789" $test_home/b1
-vault-sync -b -a export $test_home/b1 $storage || error 22 "copy existed with $?"
